learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'learning_log.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
''' learning_logs URL 패턴 정의 '''

from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 홈페이지
    url(r'^$', views.index, name='index'),
    # 주제표시?
    url(r'^topics/$', views.topics, name='topics'),
    # 주제 하나에 대한 세부사항 페이지
    #url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^topics/(?P<topic_id>[0-9]+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    url(r'^edit_entry/(?P<topic_id>\d+)/delete/(?P<entry_id>\d+)/$', views.entry_delete, name='entry_delete'),

    url(r'^topics/(?P<topic_id>\d+)/delete/(?P<comment_id>\d+)$', views.comment_delete, name='comment_delete'),

    url(r'^topics/(?P<topic_id>[0-9]+)/comment/(?P<entry_id>\d+)/$', views.add_comment, name='add_comment'),
    url(r'^topics/(?P<topic_id>[0-9]+)/edit/(?P<entry_id>\d+)/comment/(?P<comment_id>\d+)$', views.edit_comment, name='edit_comment'),

    url(r'^nsight$', views.nsight, name='nsight'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 로그인 페이지
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Topic(models.Model):
    ''' 사용자가 공부하는 주제 '''
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        ''' 모델에 관한 정보를 문자열 형태로 반환 '''
        return self.text

class Entry(models.Model):
    ''' 주제에 관한 내용 '''
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entires'

    def __str__(self):
        if len(self.text) < 10 :
            return self.text
        else :
            return self.text[:10] + "...."


        #return self.text[:20] + "..."
        '''
        if self.text[:20] < 20:
            return self.text[:20] + "..."
        else :
            return self.text
        '''

## 추가
class Comment(models.Model):
    post = models.ForeignKey(Entry, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

learning_logs/forms.py
from django import forms
from .models import Topic, Entry, Comment

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('author', 'text',)

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry, Comment
from .forms import TopicForm, EntryForm, CommentForm

# Create your views here.

def index(request):
    ''' home page '''
    return render(request, 'learning_logs/index.html')

def nsight(request):
    url = "http://api.nsight.navercorp.com/monapi/api/request?r=R-20150923-001&k=dev-cloudojt001-ncl&rt=img"
    return render(request, 'learning_logs/nsight.html', {'url': url})

@login_required
def topics(request):
    ''' 주제를 모두 표시 '''
    #topics = Topic.objects.order_by('date_added')  # 모든 사용자 접근가능
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')  # 필터를 거쳐 로그인한 사용자만 접근 가능

    context = {'topics' : topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    ''' 주제 하나와 연결된 모든 항목을 표시 '''
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user: # 주제가 현재 사용자의 것인지 확인
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    ''' 새 주제 추가 '''
    if request.method != 'POST':
        # 들어온 데이터가 없을 때는 새 폼을 만듭니다.
        form = TopicForm()
    else:
        # POST 데이터를 받아서 처리
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            #form.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    ''' 특정 주제에 관한 새 항목을 추가 '''
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        #전송된 데이터가 없으므로 빈 폼 생성
        form = EntryForm()
    else :
        # 받은 데이터를 POST 처리
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    ''' 기존항목 편집 '''
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http4Http404

    if request.method != 'POST':
        # 첫 요청이므로 폼을 현재 텍스트로 채움
        form = EntryForm(instance=entry)
    else :
        # POST 데이터를 받았을때 받은 데이터 처리
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def entry_delete(request, entry_id, topic_id):
    entry = Entry.objects.get(id=entry_id)
    entry.delete()
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user: # 주제가 현재 사용자의 것인지 확인
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    #return render(request, 'learning_logs/topic.html', context)
    return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))


# 추가
def add_comment(request, topic_id, entry_id):
    post = Entry.objects.get(id=entry_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            #return redirect('learning_logs.views.topics', pk=post.pk)
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))
    else:
        form = CommentForm()
    return render(request, 'learning_logs/add_comment.html', {'form': form})


# 삭제 버튼 구현
def comment_delete(request, topic_id, comment_id):
    entry = Comment.objects.get(id=comment_id)
    entry.delete()

    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}

    return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

# 수정
def edit_comment(request, topic_id, entry_id, comment_id):
    entry = Entry.objects.get(id=entry_id)
    comment = Comment.objects.get(id=comment_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http4Http404

    if request.method != 'POST':
        # 첫 요청이므로 폼을 현재 텍스트로 채움
        form = CommentForm(instance=comment)
    else :
        # POST 데이터를 받았을때 받은 데이터 처리
        form = CommentForm(instance = comment, data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'comment': comment, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_comment.html', context)

learning_logs/templates/learning_logs/add_comment.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1><a href="{% url 'learning_logs:topics' %}">New comment</a></h1>

    <form method="post" >
      {% csrf_token %}
        <!--{{ form.as_p }}-->
        {% bootstrap_form form %}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>
  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
        </div>

      <div class="navbar" class="navbar-collapse collapse">
        <ul>
          <li><a href="{% url 'learning_logs:index' %}">Home</a></li>
          <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a>Hello, {{ user }}. </a></li>
          <li><a href="{% url 'users:logout' %}">log out</a></li>
          {% else %}
          <li><a href="{% url 'users:register' %}">register</a></li>
          <li><a href="{% url 'users:login' %}">log in</a></li>
          {% endif %}
        </ul>

      </div> <!-- /.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <div class="page-header">
      {% block header %} {% endblock header %}
    </div>
    <div>
      {% block content %} {% endblock content %}
    </div>
  </div> <!-- container -->


  </body>
</html>

learning_logs/templates/learning_logs/content.html
{% extends "learning_logs/topic.html" %}
{% load bootstrap3 %}

{% block header %}
  <a href="{% url 'learning_logs:topics' %}"><h1>{{ topic }}</h1></a>
{% endblock header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>
  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
          </small>
        </h3>
      </div>
      <div class="pannel-body">

        <a href="topic.html">{{ entry.text | linebreaks }}</a>
          <p class="totop">
            <a href="#top">Back to top</a>
          </p>
        <!-- 여기까지 버튼 -->


      </div>
    </div>
  {% empty %}
    여기는 아닌데~~?
  {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/edit_comment.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h3><a href="{% url 'learning_logs:topics' %}"> Edit Comment </a></h3>
{% endblock header %}

{% block content %}
  <form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <!--{{ form.as_p }}-->

    {% buttons %}
      <button class="btn btn-default"><a href="{% url 'learning_logs:topic' topic.id %}">이전으로가기</a></button>
      &nbsp;    &nbsp;
      <button name="submit" class="btn btn-default">저장</button>
      &nbsp;  &nbsp;  &nbsp;  &nbsp;


    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h3><a href="{% url 'learning_logs:topics' %}"> Edit Entry </a></h3>
<script type="text/javascript"></script>
{% endblock header %}

{% block content %}
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <!--{{ form.as_p }}-->

    {% buttons %}
      <button class="btn btn-default"><a href="{% url 'learning_logs:topic' topic.id %}">이전으로가기</a></button>
      &nbsp;    &nbsp;
      <button name="submit" class="btn btn-default">저장</button>
      &nbsp;  &nbsp;  &nbsp;  &nbsp;
      <!--<button class="btn btn-default" value="submit"><a href="delete">삭제</a></button>-->
      <button class="btn btn-default" value="submit">
        <a href="{% url 'learning_logs:entry_delete' entry_id=entry.id topic_id=topic.id %}">삭제</a>
      </button>

    {% endbuttons %}
</form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %} {% block header %}
<div class="jumbotron">
  <h1>Doomba DooDoomBa.</h1>
</div>
<script type="text/javascript">
  function showhide(obj) {
    var seogd = document.getElementById(obj);
    if (seogd.style.display == 'none') { // 만약 seogd가 none이 아니면 즉, 보여지는 상태이면
      seogd.style.display = ''; // seogd를 숨기고
    } else {
      seogd.style.display = 'none'; // seogd이 숨김 상태이면 나타내라
    }
  }
</script>
{% endblock header %} {% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an Acoount</a>
    to make your own Learning Log, and list the topics you're learning about.
  </h2>
  <h2>
    <div class="pannel-body">
      <a href="{% url 'learning_logs:nsight' %}">dev-cloudojt001-ncl</a>
    </div>

  </h2>
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block content %}

<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>Add a new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
  {% csrf_token %}
  <!--{{ form.as_p }}-->
  {% bootstrap_form form %}
  <button name='submit'>add entry</button>
</form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new topic :  </h2>
{% endblock header %}

{% block content %}
  <form class="form" action="{% url 'learning_logs:new_topic' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add Topic</button>
    {% endbuttons%}
  </form>
{% endblock content %}

learning_logs/templates/learning_logs/nsight.html
{% extends "learning_logs/base.html" %} {% block header %}

<div class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <h2>dev-cloudojt001-ncl</h2>
  </a>
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
    <a class="dropdown-item" href="#" id="1.1.1.1" onclick="graph(id);">CPU 총 사용률</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#" id="1.1.1.2" onclick="graph(id);">CPU 가동률</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#" id="1.1.3.1" onclick="graph(id);">메모리 총 사용률</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#" id="1.1.4.1" onclick="graph(id);">스왑 총 사용률</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="#" id="1.1.5.1" onclick="graph(id);">디스크 사용률</a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" id="1.1.1.1" onclick="graph(id);">test</a>
  </div>
</div>
	<button id="addDataset">Add Dataset</button>
<script type="text/javascript" language="JavaScript">



// var colorNames = Object.keys(window.chartColors);
// document.getElementById('addDataset').addEventListener('click', function() {
//   var colorName = colorNames[config.data.datasets.length % colorNames.length];
//   var newColor = window.chartColors[colorName];
//   var newDataset = {
//     label: 'Dataset ' + config.data.datasets.length,
//     borderColor: newColor,
//     backgroundColor: color(newColor).alpha(0.5).rgbString(),
//     data: [],
//   };
//   for (var index = 0; index < config.data.labels.length; ++index) {
//     newDataset.data.push(randomScalingFactor());
//   }
//   config.data.datasets.push(newDataset);
//   window.myLine.update();
// });
//

  function layer_toggle(obj) {
    if (obj.style.display == 'none') obj.style.display = 'block';
    else if (obj.style.display == 'block') obj.style.display = 'none';
  }
</script>

<script>
  var graph = function(parm) {
    var graph_data = [];
    var title_name, srv_name, api_key;

    if (parm == "1.1.1.1") {
      title_name = "CPU 총 사용률";
    } else if (parm == "1.1.1.2") {
      title_name = "CPU 가동률";
    } else if (parm == "1.1.3.1") {
      title_name = "메모리 총 사용률";
    } else if (parm == "1.1.4.1") {
      title_name = "스왑 총 사용률";
    } else if (parm == "1.1.5.1") {
      title_name = "디스크 사용률";
    }
    srv_name = 'dev-cloudojt001-ncl';

    var dt = new Date();
    var day = dt.getDate();
    var month = dt.getMonth() + 1;
    var year = dt.getFullYear();
    var hour = dt.getHours();
    var minute = dt.getMinutes();
    var tdt = year + "" + ("0" + month).slice(-2) + "" + ("0" + day).slice(-2) + "" + ("0" + hour).slice(-2) + "" + ("0" + minute).slice(-2);
    //("0"+custdate.getDate()).slice(-2)
    var custdate = new Date(dt);
    custdate.setHours(custdate.getHours() - 4); // 몇시간 전데이터 받을지?
    var fdt = custdate.getFullYear() + "" + ("0" + (custdate.getMonth() + 1)).slice(-2) + "" + ("0" + custdate.getDate()).slice(-2) + "" + ("0" + custdate.getHours()).slice(-2) + "" + ("0" + custdate.getMinutes()).slice(-2);

    //console.log("custdate: "+custdate);
    //console.log("fdt: "+fdt);
    //console.log("tdt: "+tdt);
    var api_key = 'R-20150923-001';
    var url_result = 'http://api.nsight.navercorp.com/monapi/api/request?r=' + api_key + '&k=' + srv_name + '&rt=json&data=' + parm + '&fdt=' + fdt + '&tdt=' + tdt
    console.log(url_result)

    var graph_data_x = [], graph_data_y = [];
    $.ajax({
      url: url_result,
      type: 'get',
      dataType: 'json',
      success: function(data) {
        var jdata = data['result']['0']['rows'];
        for (var i = 0; i < jdata.length; i++) {
          graph_data_x.push(new Date(jdata[i]['time'] * 1000));
          graph_data_y.push(parseFloat(jdata[i]['value']));
          //console.log(new Date(jdata[i]['time'] * 1000 - 1000 * 60 * 60)); //한시간후
        }
        myChart.update(); // 차트에 데이터 업로드
      }
    })

    $("canvas#myChart").remove();
    $("div#pannel-body").append('<canvas id="myChart"></canvas>');

    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
      type: 'line',
      data: {
        labels: graph_data_x,
        datasets: [{
          label: title_name,
          data: graph_data_y,
          backgroundColor: "rgba(54, 162, 235, 0.2)"
        }]
      },
      options: {
        title: {
          display: true,
          text: srv_name
        },
        scales: {
          xAxes: [{
            display: true,
            type: 'time',
            format: "HH:mm a",

            position: 'bottom',
            beginAtZero: true,
            time: {
              unit: 'minute',
              unitStepSize: 30,
              displayFormats: {
                'minute': 'h:mm a',
                'hour': 'h:mm a'
              }
            }
          }],
          yAxes: [{
            display: true,
            ticks: {
              beginAtZero: true,
              type: 'linear',
              position: 'left',
              stepSize: 20,
              callback: function(tick) {
                return tick.toString() + '%';
              }
            }
          }]
        },
      }
    });

  }
</script>

{% endblock header %} {% block content %}
<!-- Search Button
<div style="display:none">
  <input type="text" id="parm" />
  <input type="button" value="send" onclick="graph();" />
</div>
-->
<div id="pannel-body" style="height: 370px; width: 100%;">
  <canvas id="myChart"></canvas>
</div>
<script src="http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.13.0/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.1.4/Chart.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.js"></script>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %} {% load bootstrap3 %} {% block header %}
<meta charset="utf-8">
<a href="{% url 'learning_logs:topics' %}"><h1>{{ topic }}</h1></a>
<!-- 자바 스크립트로 더보기 버튼 구현
<script type="text/javascript">
var bDisplay = true;
function doDisplay() {
  var con = document.getElementById("myDIV");
  if(con.style.display=='none'){
    con.style.display = 'block';
  }else{
    con.style.display = 'none';
  }
}
</script>
-->

<script type="text/javascript">
  function showhide(obj) {
    var seogd = document.getElementById(obj);
    if (seogd.style.display == 'none') { // 만약 seogd가 none이 아니면 즉, 보여지는 상태이면
      seogd.style.display = ''; // seogd를 숨기고
    } else {
      seogd.style.display = 'none'; // seogd이 숨김 상태이면 나타내라
    }
  }
</script>

{% endblock header %} {% block content %}
<p>
  <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
</p>
{% for entry in entries %}
<div class="panel panel-default">
  <div class="panel-heading">
    <h3>
      {{ entry.date_added|date:'Y년 M d일 H시 i분' }}
      <small style="float:right">
        <a href="{% url 'learning_logs:add_comment' topic.id entry.id %}">comment</a>
      </small>
      <small style="float:right">
        <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>  &nbsp;    &nbsp;  &nbsp;    &nbsp;
      </small>
    </h3>
  </div>
  <div class="pannel-body">
    <a href="javascript:showhide({{ entry.id }});">{{ entry }}</a>
    <div id="{{ entry.id }}" style="display:none">
      {{ entry.text | linebreaks }}
    </div>
    <!-- Comment -->
    <hr> {% for comment in entry.comments.all %}
    <div class="pannel-body">
      <div class="pannel-body">
        <strong>작성자 : {{ comment.author }}</strong> &nbsp; &nbsp; {{ comment.created_date|date:'Y년 M d일 H시 i분' }}

        <button class="btn btn-default" value="submit" style="float:right"><a href="{% url 'learning_logs:comment_delete' topic.id comment.id %}">삭제</a></button>
        <button class="btn btn-default" value="submit" style="float:right"><a href="{% url 'learning_logs:edit_comment' topic.id entry.id comment.id %}">수정</a></button>

        <button class="btn btn-default" value="submit" style="float:right"><a href="javascript:showhide({{ comment.id }}) ;">내용</a></button>
        <div id="{{ comment.id }}" style="display:none">
          <p>{{ comment.text|linebreaks }}</p>
        </div>
      </div>
    </div>
    <hr> {% empty %}
    <p>No comments :(</p>
    {% endfor %}

    <!-- <a href="javascript:doDisplay();"> {{ entry | linebreaks }} </a>
    <div id="myDIV" '''style="display:none"'''>
      {{ entry.text | linebreaks }}
      <! stlye 값을 none 으로 줄 경우 바로 내용이 나타나지 않음 >
    </div>  -->

  </div>
</div>
{% empty %} 여기는 아닌데~~? {% endfor %}
<p class="totop">
  <a href="#top">위로</a>
</p>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}
  <ul>
    {% for topic in topics %}
      <li>
        <h3><a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }}</a></h3>
      </li>
    {% empty %}
      <li> 비어있다 ~ </li>
    {% endfor %}
  </ul>
  <br><br>

  <h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic </a></h3>
{% endblock content %}