learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'learning_log.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

learning_logs/urls.py
''' learning_logs URL 패턴 정의 '''

from django.conf.urls import url, include
from . import views

urlpatterns = [
    # 홈페이지
    url(r'^$', views.index, name='index'),
    # 주제표시?
    url(r'^topics/$', views.topics, name='topics'),
    # 주제 하나에 대한 세부사항 페이지
    #url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^topics/(?P<topic_id>[0-9]+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    url(r'^edit_entry/(?P<topic_id>\d+)/delete/(?P<entry_id>\d+)/$', views.entry_delete, name='entry_delete'),

    url(r'^topics/(?P<topic_id>\d+)/delete/(?P<comment_id>\d+)$', views.comment_delete, name='comment_delete'),

    url(r'^topics/(?P<topic_id>[0-9]+)/comment/(?P<entry_id>\d+)/$', views.add_comment, name='add_comment'),
    url(r'^topics/(?P<topic_id>[0-9]+)/edit/(?P<entry_id>\d+)/comment/(?P<comment_id>\d+)$', views.edit_comment, name='edit_comment'),

    url(r'^nsight$', views.nsight, name='nsight'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 로그인 페이지
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def logout_view(request):
    ''' 로그 아웃 '''
    logout(request)
    print("Logout\n\n\n\n")
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    ''' 새 사용자 등록 '''
    if request.method != 'POST':
        # 빈 등록 폼을 표시
        form = UserCreationForm()
        print("새로 생성\n\n\n\n\n")
    else:
        # 전송 받은 폼을 처리
        form = UserCreationForm(data=request.POST)


        if form.is_valid():
            new_user = form.save()
            # 새 사용자를 로그인 시키고 홈페이지로 리다이렉트 시킴
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            print("생성된놈 로그인\n\n\n\n")
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h2>Log in to your account.</h2>
{% endblock header %}


{% block content %}
<form class="form" action="{% url 'users:login' %}" method="post">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">Log in</button>
  {% endbuttons %}

  <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
</form>
{% endblock content %}

users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
 <h2> New Account </h2>
{% endblock header %}

{% block content %}
  <form action="{% url 'users:register' %}" method="post" class="form">
    {% csrf_token %}
      <!--{{ form.as_p }}-->
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit" class="btn btn-primary">가입완료</button>
      {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
  </form>
{% endblock content %}